# name: Deploy Cloud Functions
# on:
#  workflow_dispatch:
#  push:
#    branches:
#      — main
#    paths:
#      — ‘functions/**’
# jobs:
#  build_and_deploy:
#    runs-on: ubuntu-latest
#    steps:
#      — uses: actions/checkout@v2
#      — uses: actions/setup-node@v1
#      — uses: actions/cache@v2
#        with:
#          path: ~/.npm
#          key: ${{ runner.os }}-node-${{ hashFiles(‘**/functions/package-lock.json’) }}
#  restore-keys: |
#  ${{ runner.os }}-node-
#      — name: Build Cloud Functions
#        run: cd functions && npm ci
#      — name: Create SA key
#        run: echo ‘${{ secrets.GCP_SA_KEY }}’ > $HOME/gcloud.json
#      — name: Deploy Cloud Functions
#        run: export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && npx firebase-tools deploy --only functions --json

name: Deploy to Firebase Functions on merge
"on":
  push:
    branches:
      - main
env:
  CI: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install npm packages"
        run: npm install
        working-directory: "functions"
      - name: "Deploy to Firebase"
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.GCP_SA_KEY }}"
          expires: 30d
          projectId: PROJECT_ID